<?
$aMenuLinks = Array(
    Array(
        "Фотообои",
        "/produktsiya/fotooboi/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Плакаты",
        "/produktsiya/plakaty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вывески",
        "/produktsiya/vyveski/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Стенды",
        "/produktsiya/stendy/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Картины",
        "/produktsiya/kartiny/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Для авто",
        "/produktsiya/nakleyki-dlya-avto/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Билборды",
        "/produktsiya/bilbordy/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "3 метра",
        "/produktsiya/3-metra/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "5 метров",
        "/produktsiya/5-metrov/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "А0",
        "/produktsiya/a0/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "А1",
        "/produktsiya/a1/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "А2",
        "/produktsiya/a2/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "А3",
        "/produktsiya/a3/",
        Array(),
        Array(),
        ""
    )
);
?>